# Configurations for containers in Github Actions ci

version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  ts-backend:
    build:
      context: ./backend/typescript
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
    depends_on:
      - db-test
    environment:
      - POSTGRES_DB=testing_yay
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_TEST_HOST=community-fridge-kw_db-test_1
  db-test:
    image: postgres:12-alpine
    ports:
      - 5430:5432
    environment:
      - POSTGRES_DB=testing_yay
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
