import {
  CreateSchedulingDTO,
  SchedulingDTO,
  DayPart,
  Status,
  Frequency,
} from "../types";

export const RECURRING_DONATION_ID = "1";

export const testUsersDb = [
  {
    first_name: "Test",
    last_name: "User",
    auth_id: "test id",
    role: "Donor",
    email: "test@email.com",
  },
  {
    first_name: "Test",
    last_name: "User 2",
    auth_id: "test id 2",
    role: "Donor",
    email: "test2@email.com",
  },
  {
    first_name: "Test",
    last_name: "User 3",
    auth_id: "test id 3",
    role: "Volunteer",
    email: "test3@email.com",
  },
  {
    first_name: "Test",
    last_name: "User 4",
    auth_id: "test id 4",
    role: "Volunteer",
    email: "test4@email.com",
  },
];

export const testDonorsDb = [
  {
    user_id: 1,
    donor_type: "LocalBusiness",
    business_name: "Test Name 1",
  },
  {
    user_id: 2,
    donor_type: "IndividualDonor",
    business_name: "Test Name 2",
  },
];

export const testVolunteersDb = [
  {
    user_id: 3,
  },
  {
    user_id: 4,
  },
];

export const testSchedules: CreateSchedulingDTO[] = [
  {
    donorId: "1",
    categories: ["Dry packaged goods"],
    size: "medium",
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2021-09-01T09:00:00.000Z"),
    endTime: new Date("2021-09-01T10:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: true,
    volunteerTime: "8:00 AM",
    frequency: Frequency.ONE_TIME,
    notes: "these are the notes",
    volunteerId: "1",
  },
  {
    donorId: "2",
    categories: ["Non-perishables", "Tea and coffee"],
    size: "medium",
    isPickup: true,
    volunteerTime: "8:00 AM",
    pickupLocation: "location",
    dayPart: DayPart.MORNING,
    startTime: new Date("2021-09-01T09:00:00.000Z"),
    endTime: new Date("2021-09-01T10:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: true,
    frequency: Frequency.DAILY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2021-09-03T00:00:00.000Z"),
    notes: "these are the copied notes",
    volunteerId: "1",
  },
  {
    donorId: "1",
    categories: ["Fresh produce"],
    size: "Large",
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2022-03-01T08:00:00.000Z"),
    endTime: new Date("2022-03-01T09:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: false,
    frequency: Frequency.WEEKLY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2022-03-20T00:06:00.000Z"),
    notes: "these are the copied notes",
  },
  {
    donorId: "1",
    categories: ["Fresh produce"],
    size: "Small",
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2022-04-01T08:00:00.000Z"),
    endTime: new Date("2022-04-01T09:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: false,
    frequency: Frequency.MONTHLY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2022-06-23T00:06:00.000Z"),
    notes: "these are the copied notes",
  },
  {
    donorId: "1",
    categories: ["Fresh produce"],
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2022-05-01T00:08:00.000Z"),
    endTime: new Date("2022-05-01T00:06:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: false,
    frequency: Frequency.MONTHLY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2021-10-01T00:06:00.000Z"),
    notes: "these are the copied notes",
  },
];

export const expectedOneTimeSchedulingResponse: SchedulingDTO = {
  id: "1",
  donorId: "1",
  categories: ["Dry packaged goods"],
  size: "medium",
  isPickup: false,
  dayPart: DayPart.MORNING,
  startTime: new Date("2021-09-01T09:00:00.000Z"),
  endTime: new Date("2021-09-01T10:00:00.000Z"),
  status: Status.PENDING,
  volunteerNeeded: true,
  volunteerTime: "8:00 AM",
  frequency: Frequency.ONE_TIME,
  notes: "these are the notes",
  volunteerId: "1",
  pickupLocation: null,
  recurringDonationEndDate: null,
  recurringDonationId: null,
};

export const expectedDailySchedulingResponse: SchedulingDTO[] = [
  {
    id: "1",
    donorId: "2",
    categories: ["Non-perishables", "Tea and coffee"],
    size: "medium",
    isPickup: true,
    volunteerTime: "8:00 AM",
    pickupLocation: "location",
    dayPart: DayPart.MORNING,
    startTime: new Date("2021-09-01T09:00:00.000Z"),
    endTime: new Date("2021-09-01T10:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: true,
    frequency: Frequency.DAILY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2021-09-03T00:00:00.000Z"),
    notes: "these are the copied notes",
    volunteerId: "1",
  },
  {
    id: "2",
    donorId: "2",
    categories: ["Non-perishables", "Tea and coffee"],
    size: "medium",
    isPickup: true,
    volunteerTime: "8:00 AM",
    pickupLocation: "location",
    dayPart: DayPart.MORNING,
    startTime: new Date("2021-09-02T09:00:00.000Z"),
    endTime: new Date("2021-09-02T10:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: true,
    frequency: Frequency.DAILY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2021-09-03T00:00:00.000Z"),
    notes: "these are the copied notes",
    volunteerId: "1",
  },
];

export const expectedWeeklySchedulingResponse: SchedulingDTO[] = [
  {
    id: "1",
    donorId: "1",
    categories: ["Fresh produce"],
    size: "Large",
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2022-03-01T08:00:00.000Z"),
    endTime: new Date("2022-03-01T09:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: false,
    frequency: Frequency.WEEKLY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2022-03-20T00:06:00.000Z"),
    notes: "these are the copied notes",
    pickupLocation: null,
    volunteerId: null,
    volunteerTime: null,
  },
  {
    id: "2",
    donorId: "1",
    categories: ["Fresh produce"],
    size: "Large",
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2022-03-08T08:00:00.000Z"),
    endTime: new Date("2022-03-08T09:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: false,
    frequency: Frequency.WEEKLY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2022-03-20T00:06:00.000Z"),
    notes: "these are the copied notes",
    pickupLocation: null,
    volunteerId: null,
    volunteerTime: null,
  },
  {
    id: "3",
    donorId: "1",
    categories: ["Fresh produce"],
    size: "Large",
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2022-03-15T08:00:00.000Z"),
    endTime: new Date("2022-03-15T09:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: false,
    frequency: Frequency.WEEKLY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2022-03-20T00:06:00.000Z"),
    notes: "these are the copied notes",
    pickupLocation: null,
    volunteerId: null,
    volunteerTime: null,
  },
];

export const expectedMonthlySchedulingResponse: SchedulingDTO[] = [
  {
    id: "1",
    donorId: "1",
    categories: ["Fresh produce"],
    size: "Small",
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2022-04-01T08:00:00.000Z"),
    endTime: new Date("2022-04-01T09:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: false,
    frequency: Frequency.MONTHLY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2022-06-23T00:06:00.000Z"),
    notes: "these are the copied notes",
    pickupLocation: null,
    volunteerId: null,
    volunteerTime: null,
  },
  {
    id: "2",
    donorId: "1",
    categories: ["Fresh produce"],
    size: "Small",
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2022-04-29T08:00:00.000Z"),
    endTime: new Date("2022-04-29T09:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: false,
    frequency: Frequency.MONTHLY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2022-06-23T00:06:00.000Z"),
    notes: "these are the copied notes",
    pickupLocation: null,
    volunteerId: null,
    volunteerTime: null,
  },
  {
    id: "3",
    donorId: "1",
    categories: ["Fresh produce"],
    size: "Small",
    isPickup: false,
    dayPart: DayPart.MORNING,
    startTime: new Date("2022-05-27T08:00:00.000Z"),
    endTime: new Date("2022-05-27T09:00:00.000Z"),
    status: Status.PENDING,
    volunteerNeeded: false,
    frequency: Frequency.MONTHLY,
    recurringDonationId: RECURRING_DONATION_ID,
    recurringDonationEndDate: new Date("2022-06-23T00:06:00.000Z"),
    notes: "these are the copied notes",
    pickupLocation: null,
    volunteerId: null,
    volunteerTime: null,
  },
];
