const textStyles = {
  mobileHeader1: {
    fontFamily: "Inter, sans-serif",
    fontWeight: "bold",
    lineHeight: "38px",
    fontSize: "28px",
    letterSpacing: "-0.01rem",
  },
  mobileHeader2: {
    fontFamily: "Inter, sans-serif",
    fontSize: "24px",
    lineHeight: "32px",
    fontWeight: "bold",
    letterSpacing: "-0.01rem",
  },
  mobileHeader3: {
    fontFamily: "Inter, sans-serif",
    fontWeight: "bold",
    fontSize: "20px",
    lineHeight: "28px",
  },
  mobileHeader4: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "28px",
  },
  mobileBody: {
    fontFamily: "Inter, sans-serif",
    fontSize: "16px",
    lineHeight: "28px",
  },
  mobileBodyBold: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 700,
    lineHeight: "22px",
  },
  mobileSmall: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "20px",
  },
  mobilePretitleBold: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 700,
    fontSize: "14px",
    lineHeight: "18px",
    letterSpacing: "0.02rem",
  },
  mobileLink: {
    fontFamily: "Inter, sans-serif",
    fontSize: "16px",
    lineHeight: "22px",
  },
  mobileCardDescription: {
    fontFamily: "Inter, sans-serif",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "20px",
  },
  calendarDate: {
    fontFamily: "Inter, sans-serif",
    fontWeight: "Bold",
    fontSize: "20px",
    lineHeight: "28px",
  },
  desktopSmall: {
    fontFamily: "Inter, sans-serif",
    fontSize: "14px",
    lineHeight: "16px",
    color: "black",
  },
  desktopBodyBold: {
    fontFamily: "Inter, sans-serif",
    fontWeight: "Bold",
    fontSize: "16px",
    lineHeight: "19px",
    color: "black",
  },
  desktopHeader: {
    fontFamily: "Inter, sans-serif",
    fontWeight: "Bold",
    fontSize: "24px",
    lineHeight: "34px",
    color: "black",
  },
  desktopHeader2: {
    fontFamily: "Inter, sans-serif",
    fontWeight: "Bold",
    fontSize: "32px",
    lineHeight: "42px",
    color: "black",
  },
  desktopSubtitle: {
    fontFamily: "Inter, sans-serif",
    fontWeight: "Bold",
    fontSize: "20px",
    lineHeight: "28px",
    color: "black",
  },
  popupTitleText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "22px",
    color: "black",
  },
  popupInformationText: {
    fontFamily: "Inter, sans-serif",
    fontSize: "16px",
    lineHeight: "24px",
    color: "black",
  },
};
export default textStyles;
