# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ci"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # Install dependencies
      - name: Install dependencies
        run: yarn --cwd ./frontend/ && yarn --cwd ./backend/typescript/
      
      # Linting check
      - name: Run lint for frontend
        working-directory: ./frontend
        run: yarn lint
        
      - name: Run lint for backend
        working-directory: ./backend/typescript
        run: yarn lint
      
      # Run tests
      - name: Run tests for frontend
        working-directory: ./frontend
        run: yarn test
      
      - name: Run tests for backend
        working-directory: ./backend/typescript
        run: yarn test
      
      
